countries_ES = {
    "Afganistán": "AF",
    "Albania": "AL",
    "Alemania": "DE",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguila": "AI",
    "Antártida": "AQ",
    "Antigua y Barbuda": "AG",
    "Arabia Saudita": "SA",
    "Argelia": "DZ",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaiyán": "AZ",
    "Bahamas (las)": "BS",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Bahrein": "BH",
    "Bélgica": "BE",
    "Belice": "BZ",
    "Benín": "BJ",
    "Bermudas": "BM",
    "Belarús": "BY",
    "Bolivia (Estado Plurinacional de)": "BO",
    "Bonaire, San Eustaquio y Saba": "BQ",
    "Bosnia y Herzegovina": "BA",
    "Botsuana": "BW",
    "Brasil": "BR",
    "Brunéi Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Bhután": "BT",
    "Cabo Verde": "CV",
    "Camboya": "KH",
    "Camerún": "CM",
    "Canadá": "CA",
    "Qatar": "QA",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Chipre": "CY",
    "Colombia": "CO",
    "Comoras (las)": "KM",
    "Corea (la República Popular Democrática de)": "KP",
    "Corea (la República de)": "KR",
    "Côte d'Ivoire": "CI",
    "Costa Rica": "CR",
    "Croacia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Dinamarca": "DK",
    "Dominica": "DM",
    "Ecuador": "EC",
    "Egipto": "EG",
    "El Salvador": "SV",
    "Emiratos Árabes Unidos (los)": "AE",
    "Eritrea": "ER",
    "Eslovaquia": "SK",
    "Eslovenia": "SI",
    "España": "ES",
    "Estados Unidos de América (los)": "US",
    "Estonia": "EE",
    "Etiopía": "ET",
    "Filipinas (las)": "PH",
    "Finlandia": "FI",
    "Fiji": "FJ",
    "Francia": "FR",
    "Gabón": "GA",
    "Gambia (la)": "GM",
    "Georgia": "GE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Granada": "GD",
    "Grecia": "GR",
    "Groenlandia": "GL",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guayana Francesa": "GF",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea Bissau": "GW",
    "Guinea Ecuatorial": "GQ",
    "Guyana": "GY",
    "Haití": "HT",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungría": "HU",
    "India": "IN",
    "Indonesia": "ID",
    "Iraq": "IQ",
    "Irán (República Islámica de)": "IR",
    "Irlanda": "IE",
    "Bouvet, Isla": "BV",
    "Isla de Man": "IM",
    "Navidad, Isla de": "CX",
    "Islandia": "IS",
    "Caimán, (las) Islas": "KY",
    "Cocos / Keeling, (las) Islas": "CC",
    "Cook, (las) Islas": "CK",
    "Feroe, (las) Islas": "FO",
    "Georgia del Sur (la) y las Islas Sandwich del Sur": "GS",
    "Heard (Isla) e Islas McDonald": "HM",
    "Malvinas [Falkland], (las) Islas": "FK",
    "Marianas del Norte, (las) Islas": "MP",
    "Marshall, (las) Islas": "MH",
    "Pitcairn": "PN",
    "Salomón, Islas": "SB",
    "Turcas y Caicos, (las) Islas": "TC",
    "Islas Ultramarinas Menores de los Estados Unidos (las)": "UM",
    "Vírgenes británicas, Islas": "VG",
    "Vírgenes de los Estados Unidos, Islas": "VI",
    "Israel": "IL",
    "Italia": "IT",
    "Jamaica": "JM",
    "Japón": "JP",
    "Jersey": "JE",
    "Jordania": "JO",
    "Kazajistán": "KZ",
    "Kenia": "KE",
    "Kirguistán": "KG",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Lao, (la) República Democrática Popular": "LA",
    "Lesotho": "LS",
    "Letonia": "LV",
    "Líbano": "LB",
    "Liberia": "LR",
    "Libia": "LY",
    "Liechtenstein": "LI",
    "Lituania": "LT",
    "Luxemburgo": "LU",
    "Macao": "MO",
    "Macedonia del Norte": "MK",
    "Madagascar": "MG",
    "Malasia": "MY",
    "Malawi": "MW",
    "Maldivas": "MV",
    "Malí": "ML",
    "Malta": "MT",
    "Marruecos": "MA",
    "Martinique": "MQ",
    "Mauricio": "MU",
    "Mauritania": "MR",
    "Mayotte": "YT",
    "México": "MX",
    "Micronesia (Estados Federados de)": "FM",
    "Moldova (la República de)": "MD",
    "Mónaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Nicaragua": "NI",
    "Níger (el)": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk, Isla": "NF",
    "Noruega": "NO",
    "Nueva Caledonia": "NC",
    "Nueva Zelandia": "NZ",
    "Omán": "OM",
    "Países Bajos (los)": "NL",
    "Pakistán": "PK",
    "Palau": "PW",
    "Palestina, Estado de": "PS",
    "Panamá": "PA",
    "Papua Nueva Guinea": "PG",
    "Paraguay": "PY",
    "Perú": "PE",
    "Polinesia Francesa": "PF",
    "Polonia": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Reino Unido de Gran Bretaña e Irlanda del Norte (el)": "GB",
    "Sahara Occidental": "EH",
    "República Centroafricana (la)": "CF",
    "Chequia": "CZ",
    "Congo (el)": "CG",
    "Congo (la República Democrática del)": "CD",
    "Dominicana, (la) República": "DO",
    "Reunión": "RE",
    "Ruanda": "RW",
    "Rumania": "RO",
    "Rusia, (la) Federación de": "RU",
    "Samoa": "WS",
    "Samoa Americana": "AS",
    "Saint Barthélemy": "BL",
    "San Cristóbal y Nieves": "KN",
    "San Marino": "SM",
    "Saint Martin (parte francesa)": "MF",
    "San Pedro y Miquelón": "PM",
    "San Vicente y las Granadinas": "VC",
    "Santa Helena, Ascensión y Tristán de Acuña": "SH",
    "Santa Lucía": "LC",
    "Santo Tomé y Príncipe": "ST",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra leona": "SL",
    "Singapur": "SG",
    "Sint Maarten (parte neerlandesa)": "SX",
    "República Árabe Siria": "SY",
    "Somalia": "SO",
    "Sri Lanka": "LK",
    "Suazilandia": "SZ",
    "Sudáfrica": "ZA",
    "Sudán (el)": "SD",
    "Sudán del Sur": "SS",
    "Suecia": "SE",
    "Suiza": "CH",
    "Suriname": "SR",
    "Svalbard y Jan Mayen": "SJ",
    "Tailandia": "TH",
    "Taiwán (Provincia de China)": "TW",
    "Tanzania, República Unida de": "TZ",
    "Tayikistán": "TJ",
    "Territorio Británico del Océano Índico (el)": "IO",
    "Tierras Australes Francesas (las)": "TF",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad y Tobago": "TT",
    "Túnez": "TN",
    "Turkmenistán": "TM",
    "Turquía": "TR",
    "Tuvalu": "TV",
    "Ucrania": "UA",
    "Uganda": "UG",
    "Uruguay": "UY",
    "Uzbekistán": "UZ",
    "Vanuatu": "VU",
    "Santa Sede (la)": "VA",
    "Venezuela (República Bolivariana de)": "VE",
    "Viet Nam": "VN",
    "Wallis y Futuna": "WF",
    "Yemen": "YE",
    "Yibuti": "DJ",
    "Zambia": "ZM",
    "Zimbabue": "ZW"
}